import os


APP_NAME = os.environ['APP_NAME']
APP_SECRET = os.environ['APP_SECRET']
ADMIN_USERNAME = os.environ['ADMIN_USERNAME']
ADMIN_PASSWORD = os.environ['ADMIN_PASSWORD']
DB_CONNECTION_STRING = os.environ['DB_CONNECTION_STRING']
TELEGRAM_BOT_TOKEN = os.environ['TELEGRAM_BOT_TOKEN']
